### ISSUE TITLE
Dropbox integration reached its user limit

### ISSUE THREAD

**Issue by skllcrn** [karaggeorge/kap-dropbox#1]
![image](https://user-images.githubusercontent.com/11624407/42611239-c3fd4bd8-855a-11e8-90ef-6c8abbab6432.png)

https://github.com/wulkano/kap/issues/486

**Comment by karaggeorge** [comment]
@m2mathew Hey, I just upgraded the app to the next status and it says now it allows 500 users. I'm applying for it go to production level, but until then it has a cap of 500. Could you try again and let me know if it works?
